Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: userId
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S

  OrganizationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: organizationId
      AttributeDefinitions:
        - AttributeName: organizationId
          AttributeType: S

  DiseaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: diseaseId
      AttributeDefinitions:
        - AttributeName: diseaseId
          AttributeType: S

  WorkspaceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: userId
        - KeyType: RANGE
          AttributeName: workspaceId
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: workspaceId
          AttributeType: S

  ProgramTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: workspaceId
        - KeyType: RANGE
          AttributeName: programId
      AttributeDefinitions:
        - AttributeName: workspaceId
          AttributeType: S
        - AttributeName: programId
          AttributeType: S

  ProjectTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: programId
        - KeyType: RANGE
          AttributeName: projectId
      AttributeDefinitions:
        - AttributeName: programId
          AttributeType: S
        - AttributeName: projectId
          AttributeType: S

  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: projectId
        - KeyType: RANGE
          AttributeName: taskId
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: taskId
          AttributeType: S
