Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${{self:provider.stage}}-users
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      KeySchema:
        - KeyType: HASH
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  OrganizationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${{self:provider.stage}}-organizations
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      KeySchema:
        - KeyType: HASH
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  DiseasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${{self:provider.stage}}-diseases
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      KeySchema:
        - KeyType: HASH
          AttributeName: omim
      AttributeDefinitions:
        - AttributeName: omim
          AttributeType: S
