Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  OrganizationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  DiseaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  ProgramTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: userId
        - KeyType: RANGE
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: workspaceId
          AttributeType: S
      LocalSecondaryIndexes:
        - IndexName: WSI
          KeySchema:
            - KeyType: HASH
              AttributeName: userId
            - KeyType: RANGE
              AttributeName: workspaceId
          Projection:
            ProjectionType: "ALL"


  ProjectTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: programKey
        - KeyType: RANGE
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: programKey
          AttributeType: S
        - AttributeName: id
          AttributeType: S

  WorkspaceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: userId
        - KeyType: RANGE
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: diseaseId
          AttributeType: S
      LocalSecondaryIndexes:
        - IndexName: DSI
          KeySchema:
            - KeyType: HASH
              AttributeName: userId
            - KeyType: RANGE
              AttributeName: diseaseId
          Projection:
            ProjectionType: "ALL"

  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${{self:custom.stageConfig.pointInTimeRecoveryEnabled, false}}
      KeySchema:
        - KeyType: HASH
          AttributeName: projectId
        - KeyType: RANGE
          AttributeName: id
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: id
          AttributeType: S